[package]
name = "gridloc-lib"
version = "0.1.0"
authors = ["Cassaundra <cass@cassaundra.io>"]
edition = "2018"

[dependencies]
ndarray = "0.14"
rand = "0.8"

[lib]
name = "gridloc"
path = "src/lib.rs"
test = true
